version: "3.8"

networks:
  hazar:
    driver: bridge

services:
  postgres:
    networks:
      - hazar
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - db:/var/lib/postgresql/data

  hazar:
    networks:
      - hazar
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    privileged: true  # --privileged mode
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  prometheus:
    networks:
      - hazar
    image: prom/prometheus:latest
    container_name: prometheus 
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    networks:
      - hazar
    image: grafana/grafana:latest
    container_name: grafana 
    ports:
      - 3000:3000
    volumes:
      - ./:/hazar_yer_istasyonu_2024/datasources.yml

  loki:
    networks:
      - hazar
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
    ports:
      - "3100:3100"
    command: "-config.file=/etc/loki/local-config.yml"


volumes:
  db: